#!/bin/bash

# Function to check internet connection
check_internet_connection() {
    echo "Checking internet connection..."
    while ! ping -c 1 goole.com &> /dev/null; do
        echo "No internet connection. Retrying in 5 seconds..."
        sleep 5
    done
    echo "Internet connection established."
}

# Function to start Python script in a new Bash shell
start_python_script() {
    nohup xterm -hold -e '/usr/bin/python3 /home/pi/Desktop/aws_rng/rng_collect.py' &
    nohup xterm -hold -e '/usr/bin/python3 /home/pi/Desktop/aws_rng/send_aws.py' &
}


# Main script

check_internet_connection
start_python_script >/dev/null 2>&1 &

echo "Script completed."